#demonstration of operators
a=int(input("ENTER a value:"))
b=int(input("ENTER b value:"))
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a//b=",a//b)
print("a%b=",a%b)
print("a**b=",a**b)
print("a&b=",a&b)
print("a|b=",a|b)
print("a^b=",a^b)
print("~a=",~a)
print("a<=b=",a<=b)
print("a>=b=",a>=b)
print("a<b=",a<b)
print("a>b=",a>b)
print("a==b=",a==b)
print("a!=b=",a!=b)
print(a>0 and b>0)
print(a<0 or b<0)
